extern char *std_id[];
extern char *std_type_id[];
void init_std_ids(void);

#define AT_SYM				0
#define CONS_SYM			3
#define DBL_AT_SYM			4
#define DBL_BAR_SYM             	5
#define DBL_DOLLAR_SYM			6
#define DBL_MINUS_SYM			7
#define DBL_PLUS_SYM			8
#define DBL_UNDERSCORE_SYM        	9
#define DBL_SLASH_SYM			10
#define DBL_STAR_SYM			11
#define DBL_HAT_SYM			12
#define DBL_SHARP_SYM      		13
#define DOLLAR_SYM			14
#define EQ_SYM				15
#define GE_SYM				16
#define GT_SYM				17
#define HAT_SYM				18
#define LE_SYM				19
#define LT_SYM				20
#define MINUS_SYM			21
#define NE_SYM				22
#define PLUS_SYM			23
#define SLASH_SYM			24
#define STAR_SYM			25
#define TILDE_SYM			26
#define SHARP_SYM			27
#define UNIFY1_SYM              	28
#define UNIFY2_SYM              	29
#define COLON_EQUAL_SYM			30
#define IMPLIES_SYM			31

#define ABS_ID				32
#define AGGRESSIVEHEAD_ID		33
#define AGGRESSIVELAZYHEAD_ID		34
#define AGGRESSIVELAZYTAIL_ID		35
#define AGGRESSIVELISTTOPAIR_ID		36
#define AGGRESSIVENILQ_ID		37
#define AGGRESSIVETAIL_ID		38
#define ANDF_ID				39
#define BEGINVIEW_ID			40
#define ENDVIEW_ID			41
#define AS_ID				42
#define ASSIGN_ID			43
#define ASSIGNBANG_ID			44
#define ASSIGNINIT_ID			45
#define BADINPUTX_ID			46
#define BAR_ID				47
#define BASICFILESTATUS_ID		48
#define BINDPROTECTEDUNKNOWN_ID		49
#define BINDUNKNOWN_ID			50
#define BINDUNKNOWNX_ID			51
#define SAMEUNKNOWNQQ_ID		52
#define UNKNOWN_ID			53
#define BOOLEAN_ID			54
#define CANNOTSEEKX_ID			55
#define CEILING_ID			56
#define CHANGEDIRECTORY_ID		57
#define CHAR_ID				58
#define CLOSE_ID			59
#define COMPARE_ID			60
#define COMPARISON_ID			61
#define CONTINUATIONNAME_ID		62
#define CONVERSIONX_ID			63
#define INTERNSTRING_ID			64
#define DATETIME_ID			65
#define DENOMINATOR_ID			66
#define DIV_ID				67
#define DIVIDE_ID			68
#define DOCMD_ID			69
#define DOMAINX_ID			70
#define DOWNTO_ID			71
#define EMPTYNONSHAREDBOX_ID		72
#define EMPTYSHAREDBOX_ID		73
#define EMPTYBOXQ_ID			74
#define EMPTYBOXPROC_ID			75
#define EMPTYBOXX_ID			76
#define EMPTYLISTX_ID			77
#define EQ_ID				78
#define EQUAL_ID			79
#define EXP_ID				80
#define FAIL_ID				81
#define FAILPROC_ID			82
#define FALSE_ID			83
#define FILE_ID				84
#define FLOOR_ID			85
#define FORGET_ID			86
#define FORCE_ID			87
#define FREEZEBOXRANKS_ID		88
#define NBVSETBITS_ID			89
#define GCD_ID				90
#define GETENV_ID			91
#define GETHEAPLIMIT_ID			92
#define GETSTACKLIMIT_ID		93
#define GREATER_ID			94
#define HEAD_ID				95
#define IDF_ID				96
#define IGNORE_ID			97
#define INFINITELOOPX_ID		98
#define INTEGER_ID			99
#define INVTAN_ID			100
#define LAZYDOLLAR_ID			101
#define LAZYHEAD_ID			102
#define LAZYLEFT_ID             	103
#define LAZYRIGHT_ID            	104
#define LAZYTAIL_ID             	105
#define LEFT_ID                 	106
#define LENGTH_ID               	107
#define LESS_ID                 	108
#define LIMITX_ID               	109
#define LISTTOPAIR_ID           	110
#define LN_ID                   	111
#define LOADPACKAGE_ID          	112
#define MAKEDIRECTORY_ID        	113
#define MEMX_ID                 	114
#define MOD_ID                  	115
#define NABS_ID                 	116
#define NATURAL_ID              	117
#define NBVAND_ID               	118
#define NBVMASK_ID              	119
#define NBVMAX_ID               	120
#define NBVMIN_ID               	121
#define NBVOR_ID                	122
#define NBVSHL_ID               	123
#define NBVSHR_ID               	124
#define NBVXOR_ID               	125
#define NEQ_ID                  	126
#define NIL_ID                  	127
#define NILQ_ID                 	128
#define NOCASEX_ID              	129
#define NODEFX_ID               	130
#define NOFILEX_ID              	131
#define NOT_ID                  	132
#define NUMERATOR_ID            	133
#define ODDQ_ID                 	134
#define NOTLAZYQ_ID			135
#define ORF_ID                  	136
#define OUTERIDVAL_ID           	137
#define OUTFILE_ID              	138
#define PACK_ID                 	139
#define PAUSE_ID                	140
#define NORMALPRECISION_ID		141
#define PRECISION_ID            	142
#define PRED_ID                 	143
#define PRIMITIVETRACE_ID       	144
#define NONSHAREDUNKNOWN_ID     	145
#define PROFILE_ID              	146
#define PROTECTEDNONSHAREDUNKNOWN_ID    147
#define PROTECTEDSHAREDUNKNOWN_ID       148
#define PROTECTEDUNKNOWNQ_ID    	149
#define SHAREDUNKNOWN_ID        	150
#define PUTCOMMASINNUMBERS_ID   	151
#define RANK_ID                 	152
#define RANKBOX_ID              	153
#define RATIONAL_ID             	154
#define RAWSHOW_ID              	155
#define REMOVEDIRECTORY_ID      	156
#define REMOVEFILE_ID           	157
#define RENAMEFILE_ID           	158
#define REPAUSE_ID              	159
#define REVERSE_ID              	160
#define RIGHT_ID                	161
#define SAMEUNKNOWNQ_ID         	162
#define SCANFORCHAR_ID          	163
#define SECONDSSINCETIMEZERO_ID 	164
#define SETHEAPLIMIT_ID         	165
#define SETSTACKLIMIT_ID        	166
#define HANDLEDEMONS_ID         	167
#define SHOWCONFIGURATION_ID    	168
#define SHOWENVIRONMENT_ID      	169
#define SHOWAPPLY_ID            	170
#define SIGN_ID                 	171
#define SIN_ID                  	172
#define SIZEX_ID                	173
#define SPECIESX_ID             	174
#define SQRT_ID                 	175
#define STDIN_ID                	176
#define STDOUT_ID               	177
#define STDERR_ID               	178
#define SMALLEST_ID			179
#define STRINGTOINTEGER_ID      	180
#define STRINGTONATURAL_ID      	181
#define STRINGTORATIONAL_ID     	182
#define SYSTEMX_ID              	183
#define TAIL_ID                 	184
#define NBVFIELD_ID			185
#define TESTAT_ID               	186
#define TESTX_ID                	187
#define GGEQ_SYM			188
#define LLEQ_SYM			189
#define TOOMANYFILESX_ID        	190
#define TRUE_ID                 	191
#define TRUESTDIN_ID            	192
#define TYPEOF_ID               	193
#define SUBSCRIPTX_ID			194
#define EXTRACTL_ID			195
#define UNDEFINEDPATTERNFUNCTION_ID  	196
#define LARGEST_ID			197
#define UNKNOWNQ_ID             	198
#define UNPROTECTEDUNKNOWNQ_ID  	199
#define UNRANK_ID               	200
#define UPTO_ID                 	201
#define ENVIRON_ID			202
#define PULLAPARTREAL_ID		203
#define WHERE_ID                	204
#define WILLTRAP_ID             	205
#define WRITE_ID                	206
#define WRITELN_ID              	207
#define ZEROQ_ID                	208
#define ALSO_ID				209
#define UNIFY_ID			210
#define UNIFYPRIME_ID			211
#define CONSINV_SYM			212
#define NOFONTX_ID			213
#define CLOSEDFILEX_ID			214
#define INTERRUPTX_ID			215
#define COMPOSE_ID			216
#define ENSUREX_ID			217
#define REQUIREX_ID			218
#define DIRLIST_ID			219
#define GETCWD_ID			220
#define STRINGTOREAL_ID			221
#define SHORTAPPLY_ID			222
#define FLUSHFILE_ID			223
#define NATCONST_ID			224
#define RATCONST_ID			225
#define VOLATILEMODE_ID			226
#define APPENDMODE_ID			227
#define BINARYMODE_ID			228
#define EAGERNUMTOSTRING_ID		229
#define EAGERBOOLEANTOSTRING_ID		230
#define EAGERCHARTOSTRING_ID		231
#define EAGEREXCEPTIONTOSTRING_ID 	232
#define EAGERCOMPARISONTOSTRING_ID 	233
#define EAGERFILEMODETOSTRING_ID 	234
#define EXCEPTIONDESCRIPTION_ID		235
#define EAGERFUNCTIONTOSTRING_ID 	236
#define EAGERBOXTOSTRING_ID		237
#define EAGEROUTFILETOSTRING_ID 	238
#define VALUE_ID			239
#define R1_OP_ID			240
#define L1_OP_ID			241
#define R2_OP_ID			242
#define L2_OP_ID			243
#define R3_OP_ID			244
#define L3_OP_ID			245
#define R4_OP_ID			246
#define L4_OP_ID			247
#define R5_OP_ID			248
#define L5_OP_ID			249
#define R6_OP_ID			250
#define L6_OP_ID			251
#define R7_OP_ID			252
#define L7_OP_ID			253
#define R8_OP_ID			254
#define L8_OP_ID			255
#define R9_OP_ID			256
#define L9_OP_ID			257
#define WRAP_ID				258
#define UNWRAP_ID			259
#define ENDTHREADX_ID			260
#define FAIRMERGE_ID			261
#define EVALUATING_ID			262
#define CMDMAN_ID			263
#define OCCURCHECK_ID			264
#define WRAPPEDNUMEQUAL_ID		265
#define TOPFORCE_ID			266
#define GETSTACKDEPTH_ID		267
#define CUT_ID				268
#define TERMINATEX_ID			269
#define TRYWRAP_ID			270
#define TRYUNWRAP_ID			271
#define HAT_SLASH_SYM			272
#define COMPATIFY_ID			273
/* ACTIVE_ID and ACTIVE_PRIME_ID must be consecutive, ACTIVE_ID first. */
#define ACTIVE_ID			274
#define ACTIVE_PRIME_ID			275
#define HEXTONATURAL_ID			276
#define NATURALTOHEX_ID			277
#define MAKEBOX_ID			278
#define NONSHAREDBOX_ID			279
#define SHAREDBOX_ID			280
#define NONSHAREDARRAY_ID		281
#define SHAREDARRAY_ID			282
#define INFINITENONSHAREDARRAY_ID	283
#define INFINITESHAREDARRAY_ID		284
#define ARRAYNOINIT_ID			285
#define ARRAYINIT_ID			286
#define INFINITEARRAYNOINIT_ID		287
#define INFINITEARRAYINIT_ID		288
#define FULLARRAY_ID			289
#define FULLINFINITEARRAY_ID		290
#define VARDUP_ID			291
#define INFVARDUP_ID			292
#define VARDUPNOINIT_ID			293
#define VARDUPINIT_ID			294
#define INFVARDUPNOINIT_ID		295
#define INFVARDUPINIT_ID		296
#define NONSHAREDUNKNOWNARRAY_ID 	297
#define SHAREDUNKNOWNARRAY_ID 		298
#define INFINITENONSHAREDUNKNOWNARRAY_ID 299
#define INFINITESHAREDUNKNOWNARRAY_ID 	300
#define EMPTY_BOX_BANG_ID		301
#define BOXFLAVOR_ID			302
#define NONSHARED_ID			303
#define SHARED_ID			304
#define EAGERBOXFLAVORTOSTRING_ID	305
#define FLAVOR_ID			306
#define EMPTYBOX_ID			307
#define SCANFORCHARPRIM_ID		308
#define MAKECHARSETPRIM_ID		309
#define PULL_ID				310
#define LMINUS_ID			311
#define PULLHELP_ID			312
#define SHOWCURRIEDAPPLY_ID		313
#define PULLCURRIEDHELP_ID		314
#define SKIPWS_ID			315
#define LISTEXHAUSTEDX_ID		316
#define INSTALLWRAPPULLER_ID		317
#define RETRACT_ID			318
#define OBJECTCONSTR_ID			319
#define COPY_ID				320
#define SAME_ID				321
#define COPYFLAVOR_ID			322
#define EAGERCOPYFLAVORTOSTRING_ID	323
#define MOVE_ID				324
#define CCOPY_ID			325
#define NEW_ID				326
#define CHOOSECOMMIT_ID			327
#define CHOOSETEST_ID			328
#define DOWNCAST_ID			329

#define LAST_SYM                	329   /* Largest standard id number */

#define BOOLEAN_TYPE_ID         	0
#define BOXFLAVOR_TYPE_ID		1
#define CHAR_TYPE_ID            	2
#define COMPARISON_TYPE_ID      	3
#define ENUMERATEDG_TYPE_ID     	4
#define EQG_TYPE_ID             	5
#define EXCEPTION_TYPE_ID       	6
#define HERMIT_TYPE_ID          	7
#define INTEGER_TYPE_ID         	8
#define INTEGERG_TYPE_ID        	9
#define LIST_TYPE_ID			10
#define NATURAL_TYPE_ID         	11
#define ORDERG_TYPE_ID          	12
#define OUTFILE_TYPE_ID         	13
#define RANKEDG_TYPE_ID         	14
#define RATIONAL_TYPE_ID        	15
#define RATIONALG_TYPE_ID       	16
#define RATRINGG_TYPE_ID        	17
#define REAL_TYPE_ID            	18
#define RFIELDG_TYPE_ID         	19
#define REALG_TYPE_ID        		20
#define RRINGG_TYPE_ID          	21
#define UNKNOWNKEY_TYPE_ID      	22
#define BOX_TYPE_ID			23
#define ASPECIES_TYPE_ID		24
#define ANYG_TYPE_ID			25
#define STRING_TYPE_ID			26
#define FILEMODE_TYPE_ID		27
#define OPAQUE_TYPE_ID			28
#define OPAQUE_EQ_TYPE_ID		29
#define OPAQUE_ORDER_TYPE_ID		30
#define TRANSPARENT_TYPE_ID		31
#define TRANSPARENT_EQ_TYPE_ID		32
#define TRANSPARENT_ORDER_TYPE_ID	33
#define PAIR_TYPE_ID			34
#define FUNCTION_TYPE_ID		35
#define OBJECT_TYPE_ID			36
#define COPYFLAVOR_TYPE_ID		37
#define BOXES_TYPE_ID			38
#define NEW_TYPE_ID			39

#define LAST_TYPE_ID			39  /* Largest type id value. */

