/*********************************************************************
 * File:    standard/stdids.c
 * Author:  Karl Abrahamson
 * Purpose: Holds tables of standard names.
 *********************************************************************/

#ifdef COPYRIGHT
/************************************************************************
 * Copyright (c) 1997 Karl Abrahamson					*
 * All rights reserved.							*
 *									*
 * Redistribution and use in source and binary forms, with or without	*
 * modification, are permitted provided that the following conditions	*
 * are met:								*
 *									*
 * 1. Redistributions of source code must retain the above copyright	*
 *    notice, this list of conditions and the following disclaimer.	*
 *									*
 * 2. Redistributions in binary form must reproduce the above copyright	*
 *    notice in the documentation and/or other materials provided with 	*
 *    the distribution.							*
 *									*
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY		*
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE	*
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR 	*
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE	*
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 	*
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT 	*
 * OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR 	*
 * BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,*
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE *
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,    * 
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.			*
 *									*
 ************************************************************************/
#endif

/*********************************************************************
 * This file defines the names of the things defined in stdfuns.c.   *
 *********************************************************************/

#include "../misc/misc.h"
#include "../standard/stdids.h"
#include "../tables/tables.h"

char * FARR std_id[] =
{ /* AT_SYM 			*/	"@",
  /* 				*/	NULL,
  /* 				*/	NULL,
  /* CONS_SYM			*/	"::",
  /* DBL_AT_SYM 		*/	"@@",
  /* DBL_BAR_SYM             	*/	"||",
  /* DBL_DOLLAR_SYM		*/	"$$",
  /* DBL_MINUS_SYM		*/	"--",
  /* DBL_PLUS_SYM		*/	"++",
  /* DBL_UNDERSCORE_SYM 	*/	"__",
  /* DBL_SLASH_SYM		*/	"//",
  /* DBL_STAR_SYM		*/	"**",
  /* DBL_HAT_SYM		*/	"^^",
  /* DBL_SHARP_SYM 		*/	"##",
  /* DOLLAR_SYM			*/	"$",
  /* EQ_SYM			*/	"==",
  /* GE_SYM			*/	">=",
  /* GT_SYM			*/	">",
  /* HAT_SYM			*/	"^",
  /* LE_SYM			*/	"<=",
  /* LT_SYM			*/	"<",
  /* MINUS_SYM			*/	"-",
  /* NE_SYM			*/	"=/=",
  /* PLUS_SYM			*/	"+",
  /* SLASH_SYM			*/	"/",
  /* STAR_SYM			*/	"*",
  /* TILDE_SYM			*/	"~",
  /* SHARP_SYM			*/	"#_",
  /* UNIFY1_SYM                 */      "==!",
  /* UNIFY2_SYM                 */      "==!?",
  /* COLON_EQUAL_SYM		*/	":=",
  /* IMPLIES_SYM		*/	"==>",

  /* ABS_ID			*/	"abs",
  /* AGGRESSIVEHEAD_ID		*/	"activeHead",
  /* AGGRESSIVELAZYHEAD_ID	*/	"activeLazyHead",
  /* AGGRESSIVELAZYTAIL_ID	*/	"activeLazyTail",
  /* AGGRESSIVELISTTOPAIR_ID	*/	"activeListToPair",
  /* AGGRESSIVENILQ_ID		*/	"activeNil?",
  /* AGGRESSIVETAIL_ID		*/	"activeTail",
  /* ANDF_ID			*/	"_andf_",
  /* BEGINVIEW_ID		*/	"ZZ__BeginView",
  /* ENDVIEW_ID			*/	"ZZ__EndView",
  /* AS_ID			*/	"_as_",
  /* ASSIGN_ID			*/	"Assign",
  /* ASSIGNBANG_ID		*/	"Assign!",
  /* ASSIGNINIT_ID		*/	"AssignInit",
  /* BADINPUTX_ID		*/	"badInputX",
  /* BAR_ID			*/	"_bar_",
  /* BASICFILESTATUS_ID		*/	"basicFileStatus",
  /* BINDPROTECTEDUNKNOWN_ID	*/	"BindProtectedUnknown",
  /* BINDUNKNOWN_ID		*/	"BindUnknown",
  /* BINDUNKNOWNX_ID		*/	"bindUnknownX",
  /* SAMEUNKNOWNQQ_ID		*/	"sameUnknown??",
  /* UNKNOWN_ID			*/	"unknown",
  /* BOOLEAN_ID			*/	"boolean",
  /* CANNOTSEEKX_ID		*/	"cannotSeekX",
  /* CEILING_ID			*/	"ceiling",
  /* CHANGEDIRECTORY_ID		*/	"ChangeDirectory",
  /* CHAR_ID			*/	"char",
  /* CLOSE_ID			*/	"CloseScope",
  /* COMPARE_ID			*/	"compare",
  /* COMPARISON_ID		*/	"comparison",
  /* CONTINUATIONNAME_ID	*/	"callerName",
  /* CONVERSIONX_ID		*/	"conversionX",
  /* INTERNSTRING_ID		*/	"internString",
  /* DATETIME_ID		*/	"dateTime",
  /* DENOMINATOR_ID		*/	"denominator",
  /* DIV_ID			*/	"_div_",
  /* DIVIDE_ID			*/	"divide",
  /* DOCMD_ID			*/	"doCmd",
  /* DOMAINX_ID			*/	"domainX",
  /* DOWNTO_ID			*/	"_downto_",
  /* EMPTYNONSHAREDBOX_ID	*/	"emptyNonsharedBox",
  /* EMPTYSHAREDBOX_ID		*/	"emptySharedBox",
  /* EMPTYBOXQ_ID		*/	"emptyBox?",
  /* EMPTYBOXPROC_ID		*/	"EmptyBox",
  /* EMPTYBOXX_ID		*/	"emptyBoxX",
  /* EMPTYLISTX_ID		*/	"emptyListX",
  /* EQ_ID			*/	"_eq_",
  /* EQUAL_ID			*/	"equal",
  /* EXP_ID			*/	"reNormalExp",
  /* FAIL_ID			*/	"fail",
  /* FAILPROC_ID		*/	"Fail",
  /* FALSE_ID			*/	"false",
  /* FILE_ID			*/	"basicInfile",
  /* FLOOR_ID			*/	"floor",
  /* FORGET_ID			*/	"forget",
  /* FORCE_ID			*/	"forceAll",
  /* FREEZEBOXRANKS_ID		*/	"FreezeBoxRanks",
  /* NBVSETBITS_ID		*/	"nbvSetBits",
  /* GCD_ID			*/	"gcd",
  /* GETENV_ID			*/	"getEnv",
  /* GETHEAPLIMIT_ID		*/	"getHeapLimit",
  /* GETSTACKLIMIT_ID		*/	"getStackLimit",
  /* GREATER_ID			*/	"greater",
  /* HEAD_ID			*/	"head",
  /* IDF_ID			*/	"idf",
  /* IGNORE_ID			*/	"Ignore",
  /* INFINITELOOPX_ID		*/	"infiniteLoopX",
  /* INTEGER_ID			*/	"integer",
  /* INVTAN_ID			*/	"reNormalInvtan",
  /* LAZYDOLLAR_ID		*/	"lazyDollar",
  /* LAZYHEAD_ID		*/	"lazyHead",
  /* LAZYLEFT_ID		*/	"lazyLeft",
  /* LAZYRIGHT_ID		*/	"lazyRight",
  /* LAZYTAIL_ID		*/	"lazyTail",
  /* LEFT_ID			*/	"left",
  /* LENGTH_ID			*/	"length",
  /* LESS_ID			*/	"less",
  /* LIMITX_ID			*/	"limitX",
  /* LISTTOPAIR_ID		*/	"listToPair",
  /* LN_ID			*/	"reNormalLn",
  /* LOADPACKAGE_ID		*/	"LoadPackage",
  /* MAKEDIRECTORY_ID		*/	"MakeDirectory",
  /* MEMX_ID			*/	"memoryX",
  /* MOD_ID			*/	"_mod_",
  /* NABS_ID			*/	"nabs",
  /* NATURAL_ID			*/	"natural",
  /* NBVAND_ID			*/	"nbvAnd",
  /* NBVMASK_ID			*/	"nbvMask",
  /* NBVMAX_ID			*/	"nbvMax",
  /* NBVMIN_ID			*/	"nbvMin",
  /* NBVOR_ID			*/	"nbvOr",
  /* NBVSHL_ID			*/	"nbvShl",
  /* NBVSHR_ID			*/	"nbvShr",
  /* NBVXOR_ID			*/	"nbvXor",
  /* NEQ_ID			*/	"_neq_",
  /* NIL_ID			*/	"nil",
  /* NILQ_ID			*/	"nil?",
  /* NOCASEX_ID			*/	"noCaseX",
  /* NODEFX_ID			*/	"noDefX",
  /* NOFILEX_ID			*/	"noFileX",
  /* NOT_ID			*/	"not",
  /* NUMERATOR_ID		*/	"numerator",
  /* ODDQ_ID			*/	"odd?",
  /* NOTLAZYQ_ID		*/	"notLazy?",
  /* ORF_ID			*/	"_orf_",
  /* OUTERIDVAL_ID		*/	"outerBinding",
  /* OUTFILE_ID			*/	"basicOutfile",
  /* PACK_ID			*/	"lazyPack",
  /* PAUSE_ID			*/	"Pause",
  /* NORMALPRECISION_ID		*/	"normalPrecision",
  /* PRECISION_ID		*/	"precision!",
  /* PRED_ID			*/	"pred",
  /* PRIMITIVETRACE_ID		*/	"PrimitiveTrace",
  /* NONSHAREDUNKNOWN_ID	*/	"nonsharedUnknown",
  /* PROFILE_ID			*/	"Profile",
  /* PROTECTEDNONSHAREDUNKNOWN_ID */	"protectedNonsharedUnknown",
  /* PROTECTEDSHAREDUNKNOWN_ID	*/	"protectedSharedUnknown",
  /* PROTECTEDUNKNOWNQ_ID	*/	"protectedUnknown?",
  /* SHAREDUNKNOWN_ID		*/	"sharedUnknown",
  /* PUTCOMMASINNUMBERS_ID	*/	"putCommasInNumbers!",
  /* RANK_ID			*/	"rank",
  /* RANKBOX_ID			*/	"rankBox",
  /* RATIONAL_ID		*/	"rational",
  /* RAWSHOW_ID			*/	"RawShow",
  /* REMOVEDIRECTORY_ID		*/	"RemoveDirectory",
  /* REMOVEFILE_ID		*/	"RemoveFile",
  /* RENAMEFILE_ID		*/	"RenameFile",
  /* REPAUSE_ID			*/	"Repause",
  /* REVERSE_ID			*/	"reverse",
  /* RIGHT_ID			*/	"right",
  /* SAMEUNKNOWNQ_ID		*/	"sameUnknown?",
  /* SCANFORCHAR_ID		*/	"scanForChar",
  /* SECONDSSINCETIMEZERO_ID	*/	"secondsSinceTimeZero",
  /* SETHEAPLIMIT_ID		*/	"SetHeapLimit",
  /* SETSTACKLIMIT_ID		*/	"SetStackLimit",
  /* HANDLEDEMONS_ID		*/	"standardimp" NAME_SEP_STR "handleDemons",
  /* SHOWCONFIGURATION_ID	*/	"ShowConfiguration",
  /* SHOWENVIRONMENT_ID		*/	"ShowEnvironment",
  /* SHOWAPPLY_ID		*/	"showApply",
  /* SIGN_ID			*/	"sign",
  /* SIN_ID			*/	"reNormalSin",
  /* SIZEX_ID			*/	"sizeX",
  /* SPECIESX_ID		*/	"speciesX",
  /* SQRT_ID			*/	"reNormalSqrt",
  /* STDIN_ID			*/	"stdin!",
  /* STDOUT_ID			*/	"stdout!",
  /* STDERR_ID			*/	"stderr!",
  /* SMALLEST_ID		*/	"smallest",
  /* STRINGTOINTEGER_ID		*/	"stringToInteger",
  /* STRINGTONATURAL_ID		*/	"stringToNatural",
  /* STRINGTORATIONAL_ID	*/	"stringToRational",
  /* SYSTEMX_ID			*/	"systemX",
  /* TAIL_ID			*/	"tail",
  /* NBVFIELD_ID		*/      "nbvField",
  /* TESTAT_ID			*/	"testAt",
  /* TESTX_ID			*/	"testX",
  /* GGEQ_SYM			*/	">>=",
  /* LLEQ_SYM			*/	"<<=",
  /* TOOMANYFILESX_ID		*/	"tooManyFilesX",
  /* TRUE_ID			*/	"true",
  /* TRUESTDIN_ID		*/	"trueStdin!",
  /* TYPEOF_ID			*/	"speciesOf",
  /* SUBSCRIPTX_ID		*/	"subscriptX",
  /* EXTRACTL_ID		*/	"extractL",
  /* UNDEFINEDPATTERNFUNCTION_ID */	"undefinedPatternFunction",
  /* LARGEST	 		*/	"largest",
  /* UNKNOWNQ_ID		*/	"unknown?",
  /* UNPROTECTEDUNKNOWNQ_ID	*/	"unprotectedUnknown?",
  /* UNRANK_ID			*/	"unrank",
  /* UPTO_ID			*/	"_upto_",
  /* ENVIRON_ID			*/	"sysEnvironF",
  /* PULLAPARTREAL_ID		*/	"pullApartReal",
  /* WHERE_ID			*/	"_where_",
  /* WILLTRAP_ID		*/	"willTrap",
  /* WRITE_ID			*/	"Write",
  /* WRITELN_ID			*/	"Writeln",
  /* ZEROQ_ID			*/	"zero?",
  /* ALSO_ID			*/	"_also_",
  /* UNIFY_ID			*/	"Unify",
  /* UNIFYPRIME_ID		*/	"Unify?",
  /* CONSINV_SYM		*/	"&/-",
  /* NOFONTX_ID			*/	"noFontX",
  /* CLOSEDFILEX_ID		*/	"closedFileX",
  /* INTERRUPTX_ID		*/	"interruptX",
  /* COMPOSE_ID			*/	"_o_",
  /* ENSUREX_ID			*/	"ensureX",
  /* REQUIREX_ID		*/	"requireX",
  /* DIRLIST_ID			*/	"basicDirList",
  /* GETCWD_ID			*/	"getCwd",
  /* STRINGTOREAL_ID		*/	"stringToReal",
  /* SHORTAPPLY_ID		*/	"shortApply",
  /* FLUSHFILE_ID		*/	"FlushFile",
  /* NATCONST_ID		*/	"natconst",
  /* RATCONST_ID		*/	"ratconst",
  /* VOLATILEMODE_ID		*/	"volatileMode",
  /* APPENDMODE_ID		*/	"appendMode",
  /* BINARYMODE_ID		*/	"binaryMode",
  /* EAGERNUMTOSTRING_ID	*/	"eagerNumToString",
  /* EAGERBOOLEANTOSTRING_ID	*/	"eagerBooleanToString",
  /* EAGERCHARTOSTRING_ID	*/	"eagerCharToString",
  /* EAGEREXCEPTIONTOSTRING_ID  */	"eagerExceptionToString",
  /* EAGERCOMPARISONTOSTRING_ID */	"eagerComparisonToString",
  /* EAGERFILEMODETOSTRING_ID   */	"eagerFileModeToString",
  /* EXCEPTIONDESCRIPTION_ID	*/	"exceptionDescription",
  /* EAGERFUNCTIONTOSTRING_ID   */	"eagerFunctionToString",
  /* EAGERBOXTOSTRING_ID	*/	"eagerBoxToString",
  /* EAGEROUTFILETOSTRING_ID	*/	"eagerOutfileToString",
  /* VALUE_ID			*/	"Value",
  /* R1_OP_ID			*/	"_opR1_",
  /* L1_OP_ID			*/	"_opL1_",
  /* R2_OP_ID			*/	"_opR2_",
  /* L2_OP_ID			*/	"_opL2_",
  /* R3_OP_ID			*/	"_opR3_",
  /* L3_OP_ID			*/	"_opL3_",
  /* R4_OP_ID			*/	"_opR4_",
  /* L4_OP_ID			*/	"_opL4_",
  /* R5_OP_ID			*/	"_opR5_",
  /* L5_OP_ID			*/	"_opL5_",
  /* R6_OP_ID			*/	"_opR6_",
  /* L6_OP_ID			*/	"_opL6_",
  /* R7_OP_ID			*/	"_opR7_",
  /* L7_OP_ID			*/	"_opL7_",
  /* R8_OP_ID			*/	"_opR8_",
  /* L8_OP_ID			*/	"_opL8_",
  /* R9_OP_ID			*/	"_opR9_",
  /* L9_OP_ID			*/	"_opL9_",
  /* WRAP_ID			*/	"wrap",
  /* UNWRAP_ID			*/	"safeUnwrap",
  /* ENDTHREADX_ID		*/	"endThreadX",
  /* FAIRMERGE_ID		*/	"fairMerge",
  /* EVALUATING_ID		*/	"evaluating",
  /* CMDMAN_ID			*/	"command-manager",
  /* OCCURCHECK_ID		*/	"occur-check",
  /* WRAPPEDNUMEQUAL_ID		*/	"wrappedNumberEqual",
  /* TOPFORCE_ID		*/	"force",
  /* GETSTACKDEPTH_ID		*/	"getStackDepth",
  /* CUT_ID			*/	"Cut",
  /* TERMINATEX_ID		*/	"terminateX",
  /* TRYWRAP_ID			*/	"unsafeWrap",
  /* TRYUNWRAP_ID		*/	"unsafeUnwrap",
  /* HAT_SLASH_SYM		*/	"^/",
  /* COMPATIFY_ID		*/	"compatify",
  /* ACTIVE_ID			*/	"active",
  /* ACTIVE_PRIME_ID		*/	"active?",
  /* HEXTONATURAL_ID		*/	"hexToNatural",
  /* NATURALTOHEX_ID		*/	"naturalToHexHelp",
  /* MAKEBOX_ID			*/	"makebox",
  /* NONSHAREDBOX_ID		*/	"nonsharedBox",
  /* SHAREDBOX_ID		*/	"sharedBox",
  /* NONSHAREDARRAY_ID		*/	"nonsharedArray",
  /* SHAREDARRAY_ID		*/	"sharedArray",
  /* INFINITENONSHAREDARRAY_ID 	*/	"infiniteNonsharedArray",
  /* INFINITESHAREDARRAY_ID    	*/	"infiniteSharedArray",
  /* ARRAYNOINIT_ID		*/	"arrayNoinit",
  /* ARRAYINIT_ID		*/	"arrayInit",
  /* INFINITEARRAYNOINIT_ID	*/	"infiniteArrayNoinit",
  /* INFINITEARRAYINIT_ID	*/	"infiniteArrayInit",
  /* FULLARRAY_ID		*/	"fullArray",
  /* FULLINFINITEARRAY_ID	*/	"fullInfiniteArray",
  /* VARDUP_ID			*/	"varDup",
  /* INFVARDUP_ID		*/	"infVarDup",
  /* VARDUPNOINIT_ID		*/	"varDupNoinit",
  /* VARDUPINIT_ID		*/	"varDupInit",
  /* INFVARDUPNOINIT_ID		*/	"infVarDupNoinit",
  /* INFVARDUPINIT_ID		*/	"infVarDupInit",
  /* NONSHAREDUNKNOWNARRAY_ID	*/	"nonsharedUnknownArray",
  /* SHAREDUNKNOWNARRAY_ID	*/	"sharedUnknownArray",
  /* INFINITENONSHAREDUNKNOWNARRAY_ID */ "infiniteNonsharedUnknownArray",
  /* INFINITESHAREDUNKNOWNARRAY_ID */	"infiniteSharedUnknownArray",
  /* EMPTY_BOX_BANG_ID		*/	"EmptyBox!",
  /* BOXFLAVOR_ID		*/	"boxFlavor",
  /* NONSHARED_ID		*/	"nonshared",
  /* SHARED_ID			*/	"shared",
  /* EAGERBOXFLAVORTOSTRING_ID	*/	"eagerBoxFlavorToString",
  /* FLAVOR_ID			*/	"flavor",
  /* EMPTYBOX_ID		*/	"emptyBox",
  /* SCANFORCHARPRIM_ID,	*/	"scanForCharPrim",
  /* MAKECHARSETPRIM_ID		*/	"makeCharSetPrim",
  /* PULL_ID			*/	"pull",
  /* LMINUS_ID			*/	"_lminus_",
  /* PULLHELP_ID		*/	"pullHelp",
  /* SHOWCURRIEDAPPLY_ID	*/	"showCurriedApply",
  /* PULLCURRIEDHELP_ID		*/	"pullCurriedHelp",
  /* SKIPWS_ID			*/	"skipWS",
  /* LISTEXHAUSTEDX_ID		*/	"listExhaustedX",
  /* INSTALLWRAPPULLER_ID	*/	"InstallPull",
  /* RETRACT_ID			*/	"retract",
  /* OBJECTCONSTR_ID		*/	"object!",
  /* COPY_ID			*/	"copy",
  /* SAME_ID			*/	"same",
  /* COPYFLAVOR_ID		*/	"copyFlavor",
  /* EAGERCOPYFLAVORTOSTRING_ID */	"eagerCopyFlavorToString",
  /* MOVE_ID			*/	"Move",
  /* CCOPY_ID			*/	"Copy",
  /* NEW_ID			*/	"new",
  /* CHOOSECOMMIT_ID		*/	"ChooseCommit",
  /* CHOOSETEST_ID		*/	"ChooseTest",
  /* DOWNCAST_ID		*/      "downcast"

};

char * FARR std_type_id[] =
{
  /* BOOLEAN_TYPE_ID		*/	"Boolean",
  /* BOXFLAVOR_TYPE_ID		*/	"BoxFlavor",
  /* CHAR_TYPE_ID		*/	"Char",
  /* COMPARISON_TYPE_ID		*/	"Comparison",
  /* ENUMERATEDG_TYPE_ID	*/	"ENUMERATED",
  /* EQG_TYPE_ID		*/	"EQ",
  /* EXCEPTION_TYPE_ID		*/	"ExceptionSpecies",
  /* HERMIT_TYPE_ID		*/	"()",
  /* INTEGER_TYPE_ID		*/	"Integer",
  /* INTEGERG_TYPE_ID		*/	"INTEGER",
  /* LIST_TYPE_ID		*/	"List",
  /* NATURAL_TYPE_ID		*/	"Natural",
  /* ORDERG_TYPE_ID		*/	"ORDER",
  /* OUTFILE_TYPE_ID		*/	"Outfile",
  /* RANKEDG_TYPE_ID		*/	"RANKED",
  /* RATIONAL_TYPE_ID		*/	"Rational",
  /* RATIONALG_TYPE_ID		*/	"RATIONAL",
  /* RATRINGG_TYPE_ID		*/	"RATRING",
  /* REAL_TYPE_ID		*/	"Real",
  /* RFIELDG_TYPE_ID		*/	"RFIELD",
  /* REALG_TYPE_ID		*/	"REAL",
  /* RRINGG_TYPE_ID		*/	"RRING",
  /* UNKNOWNKEY_TYPE_ID		*/	"UnknownKey",
  /* BOX_TYPE_ID		*/	"Box",
  /* ASPECIES_TYPE_ID		*/	"ASpecies",
  /* ANYG_TYPE_ID		*/	"ANY",
  /* STRING_TYPE_ID		*/	"String",
  /* FILE_MODE_TYPE_ID		*/	"FileMode",
  /* OPAQUE_TYPE_ID		*/	"OPAQUE",
  /* OPAQUE_EQ_TYPE_ID		*/	"OPAQUE_EQ",
  /* OPAQUE_ORDER_TYPE_ID	*/	"OPAQUE_ORDER",
  /* TRANSPARENT_TYPE_ID	*/	"TRANSPARENT",
  /* TRANSPARENT_EQ_TYPE_ID	*/	"TRANSPARENT_EQ",
  /* TRANSPARENT_ORDER_TYPE_ID	*/	"TRANSPARENT_ORDER",
  /* PAIR_TYPE_ID		*/	"PAIR@",
  /* FUNCTION_TYPE_ID		*/	"FUNCTION@",
  /* OBJECT_TYPE_ID		*/	"Object",
  /* COPYFLAVOR_TYPE_ID		*/	"CopyFlavor",
  /* BOXES_TYPE_ID		*/	"BOXES",
  /* NEW_TYPE_ID		*/	"NEW"
};


/****************************************************************
 *			INIT_STD_IDS				*
 ****************************************************************
 * Put the standard ids in the string table.			*
 ****************************************************************/

void init_std_ids(void)
{
  int i;
  for(i = 0; i <= LAST_SYM; i++) {
    stat_id_tb(std_id[i]);
  }
  for(i = 0; i <= LAST_TYPE_ID; i++) {
    stat_id_tb(std_type_id[i]);
  }
}

