/*********************************************************************
 * File:    parser/compiler.c
 * Purpose: main program for parser.
 * Author:  Karl Abrahamson
 *********************************************************************/

#ifdef COPYRIGHT
/************************************************************************
 * Copyright (c) 1997 Karl Abrahamson					*
 * All rights reserved.							*
 *									*
 * Redistribution and use in source and binary forms, with or without	*
 * modification, are permitted provided that the following conditions	*
 * are met:								*
 *									*
 * 1. Redistributions of source code must retain the above copyright	*
 *    notice, this list of conditions and the following disclaimer.	*
 *									*
 * 2. Redistributions in binary form must reproduce the above copyright	*
 *    notice in the documentation and/or other materials provided with 	*
 *    the distribution.							*
 *									*
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY		*
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE	*
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR 	*
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE	*
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 	*
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT 	*
 * OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR 	*
 * BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,*
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE *
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,    * 
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.			*
 *									*
 ************************************************************************/
#endif

/************************************************************************
 * This is the top level of the compiler.  It contains the main 	*
 * program and support for handling options.  It also contains		*
 * miscellaneous utilities for startup and exit.			*
 ************************************************************************/

#include <string.h>
#include <stdlib.h>
#include <sys/stat.h>
#include "../misc/misc.h"
#include <signal.h>
#ifdef UNIX
# include <sys/types.h>
# include <unistd.h>
# include <sys/time.h>
time_t time(time_t *tloc);
#endif
#ifdef MSWIN
# include <time.h>
# include <windows.h>
#endif
#include "../utils/lists.h"
#include "../utils/strops.h"
#include "../utils/filename.h"
#include "../alloc/allocate.h"
#include "../classes/classes.h"
#include "../tables/tables.h"
#include "../clstbl/classtbl.h"
#include "../clstbl/meettbl.h"
#include "../error/error.h"
#include "../parser/parser.h"
#include "../parser/asd.h"
#include "../lexer/lexer.h"
#include "../lexer/modes.h"
#include "../generate/generate.h"
#include "../patmatch/patmatch.h"
#include "../standard/stdids.h"
#include "../infer/infer.h"
#include "../dcls/dcls.h"
#ifdef DEBUG
# include "../debug/debug.h"
# include "../show/prtent.h"
#endif
#ifdef MSWIN
# include "../win/astcwin.rh"
  extern void get_profile(void);
  extern void free_profile_strings(void);
#endif

void init_exprs(void);
int yyparse(void);

/****************************************************************
 *			ideWindow				*
 ****************************************************************
 * ideWindow holds the window handle of the development		*
 * environment.  It is obtained from the command line, and used *
 * to send a message indicating that compilation is done at the *
 * end of the compile.						*
 ****************************************************************/

#ifdef MSWIN
  HWND ideWindow = 0;
#endif

/****************************************************************
 *			aso_file				*
 ****************************************************************
 * From generate.c.  This is the name of the file where the 	*
 * generated byte-code is placed.  It should be removed when 	*
 * there is a fatal error. 					*
 ****************************************************************/

extern char *aso_file;  

/****************************************************************
 *			default_import_path			*
 ****************************************************************
 * default_import_path is a list of directory names where 	*
 * imported files are to be looked for.  It is used in		*
 * preflex.c to find imports, and is set here from command line *
 * options or from environment variable AST_IMPORTS. 		*
 ****************************************************************/

extern STR_LIST *default_import_path; 

/****************************************************************
 *			CLEAN_UP_AND_EXIT			*
 ****************************************************************
 * Flush files, clean up buffers, possibly unlink output file,  *
 * and exit with status val.					*
 ****************************************************************/

void yy_delete_buffer(YY_BUFFER_STATE b);  /* From parser */

PRIVATE char there_were_errors[]   = "\nThere were errors\n";
PRIVATE char there_were_warnings[] = "\nThere were warnings\n";
PRIVATE char there_were_unsat[]    = "\nThere were unsatisfied expectations\n";

void clean_up_and_exit(int val)
{
  int result = val;

  /*-----------------------------------------------------------------*
   * Add a newline to the listing file, in case the source file does *
   * not end on a newline.					     *
   *-----------------------------------------------------------------*/

  if(LISTING_FILE != NULL) fnl(LISTING_FILE);

  /*--------------------------------------------------------------------*
   * Print messages about errors. Force status 1 if val == 0 and there	*
   * was a fatal error.							*
   *--------------------------------------------------------------------*/

  print_reports_p();
  fflush(LISTING_FILE);
  fflush(ERR_FILE);
  if(error_occurred) {
#   ifdef UNIX
      fprintf(stderr, there_were_errors);
#   else
      err_print_str(there_were_errors);
#   endif
    if(val == 0) result = 1;
  }
  else {
    if(warning_occurred) {
#     ifdef UNIX
        fprintf(stderr, there_were_warnings);
#     else
        err_print_str(there_were_warnings);
#     endif
    }

    if(printed_missing_expect_header) {
#     ifdef UNIX
        fprintf(stderr, there_were_unsat);
#     else
        err_print_str(there_were_unsat);
#     endif
    }
  }

  /*------------------------------*
   * Close the open output files. *
   *------------------------------*/

  if(LISTING_FILE != NULL) fclose(LISTING_FILE);
  if(ERR_FILE != NULL && ERR_FILE != LISTING_FILE) fclose(ERR_FILE);
  if(genf != NULL) fclose(genf);
  close_index_files(FALSE);

# ifdef DEBUG
    if(TRACE_FILE != NULL && TRACE_FILE != LISTING_FILE) fclose(TRACE_FILE);
# endif

  /*-----------------------------------------------------*
   * Close the open input files, and delete the buffers. *
   *-----------------------------------------------------*/

  while(file_info_st != NULL) {
    pop_input_file(0);
  }

  /*--------------------------------------------*
   * Unlink the .aso file if there were errors. *
   *--------------------------------------------*/

  if(result != 0 && aso_file != NULL) unlink_file(aso_file);

  /*--------------------------------------------*
   * Deallocate all allocated memory for MSWIN. *
   *--------------------------------------------*/

# ifdef MSWIN
    free_all_blocks();
    free_profile_strings();
# endif

  /*--------------------------------------------*
   * If we are instrumenting the code, then     *
   * write the instrumentation file.            *
   *--------------------------------------------*/

# ifdef INSTRUMENT
    zzwrite();
# endif

  /*--------------------------------------------*
   * For MSWIN, inform the development window   *
   * that the compile is done.                  *
   *--------------------------------------------*/

# ifdef MSWIN
    {MSG msg;
     PeekMessage(&msg, NULL, 0, 0, PM_NOREMOVE);
     PostMessage(ideWindow, CM_COMPILER_DONE, 0, 0);
    }
# endif

  exit(result);
}


/****************************************************************
 *			INTRUPT, SEGVIOL			*
 ****************************************************************
 * Process an interrupt or segmentation violation.		*
 ****************************************************************/

void intrupt(int signo_unused)
{
  signal(SIGINT, SIG_IGN);
  clean_up_and_exit(1);
}

/*------------------------------------------------------*/

PRIVATE void segviol(int signo_unused)
{
  signal(SIGSEGV, SIG_IGN);

# ifdef UNIX
    fprintf(stderr, "Segmentation violation\n");
# endif

  clean_up_and_exit(1);
}


/****************************************************************
 *				USAGE_ERR			*
 ****************************************************************
 * Complain about command line usage and die.			*
 ****************************************************************/

PRIVATE void usage_err(void)
{
  die(151);
}


/****************************************************************
 *			  GET_OUT_FILE				*
 ****************************************************************
 * Open the file named in argv[i]+k, or if that is an empty     *
 * string, to argv[*i+1], incrementing *i in the latter case,   *
 * and set *f to the new open file.  				*
 * The file is open for writing.  				*
 *								*
 * If there is a problem, such as the file already existing,	*
 * use string description as the description of the file to be  *
 * opened when communicating with the user.  Aborts the 	*
 * compiler if the file could not be opened.  			*
 *								*
 * In the special case where the file name has suffix .ast,     *
 * give a special complaint.  This is for idiots who try to     *
 * write the listing on top of the source file.			*
 *								*
 * open_mode is the mode for opening.				*
 *								*
 * If argv[i]+2 is empty and *i >= argc - 1, then print a       *
 * usage error and abort the compiler.				*
 ****************************************************************/

PRIVATE void 
get_out_file(char *description, FILE **f, int argc, char **argv, int *i,
	     char *open_mode, int k)
{
# ifdef UNIX
    struct stat stat_buf;
# endif

  /*---------------------------*
   * Get the name of the file. *
   *---------------------------*/

  char* opt = argv[*i];
  char* carg;

  if(opt[k] != '\0') carg = opt+k;
  else if(*i >= argc) usage_err();
  else carg = argv[++(*i)];

  /*-----------------------------------------------------------*
   * If the file has suffix .ast, give a special complaint     *
   * and abort.						       *
   *-----------------------------------------------------------*/

# ifdef UNIX
    if(suffix_ignore_case(".ast", carg) && stat_file(carg, &stat_buf) == 0) {
      fprintf(stderr,
	      "astc: %s \"%s\" is a source file!. I will not overwrite.", 
	      description, carg);
      clean_up_and_exit(1);
    }
# endif

  /*-----------------------------------------------------------*
   * If the file exists, ask the user if overwrite is desired. *
   *-----------------------------------------------------------*/

# ifdef UNIX
    if(stat_file(carg, &stat_buf) == 0) {
      int ch;
      fprintf(stderr,
	      "astc: %s \"%s\" exists.  Overwrite?[y|n] ", 
	      description, carg);
      ch = getchar();
      if(ch != 'y') clean_up_and_exit(1);
      ch = getchar();
      if(ch != '\n') clean_up_and_exit(1);
    }
# endif

  /*-----------------------------------------------------------*
   * Open the new file.  If the open fails, complain and exit. *
   *-----------------------------------------------------------*/

  *f = fopen_file(carg, open_mode);
  if(*f == NULL) {
    fprintf(ERR_FILE, "astc: cannot open %s\n", description);
    clean_up_and_exit(1);
  }
}


/****************************************************************
 *				DOING_EXPORT			*
 ****************************************************************
 * Return true when we are processing the export part of a      *
 * package.  For standard.asi, this includes the initialization *
 * part, since it should appear to be the export part of	*
 * standard.asi.						*
 ****************************************************************/

Boolean doing_export(void)
{
  return main_context == EXPORT_CX ||
         (compiling_standard_asi && main_context == INIT_CX);
}


/****************************************************************
 *		   SHOW_ASTC_OPTIONS				*
 ****************************************************************
 * Show the options to astc.					*
 ****************************************************************/

PRIVATE void show_astc_options(void)
{
  char filename[MAX_FILE_NAME_LENGTH];
  strcpy(filename, MESSAGE_DIR);
  strcat(filename, ASTC_OPTION_FILE);
  print_file(filename);
}


/****************************************************************
 *		   PROCESS_COMMAND_LINE_OPTIONS			*
 ****************************************************************
 * Handle the command line options in argv.  			*
 ****************************************************************/

PRIVATE int do_gen_listing = 1;          /* Default value for gen_listing */

#ifdef DEBUG
  PRIVATE Boolean print_tables = FALSE;	       /* True if should print tables
						  at end of compile. */
#endif

PRIVATE Boolean do_help = 0;                   /* True if --help is an
						  argument. */

PRIVATE Boolean do_version = 0;		       /* True if --version is an
						  argument. */

/*--------------------------------------------------------------*/

PRIVATE void process_command_line_options(int argc, char** argv)
{
  int i;
  char *opt;

  for(i = 1; i < argc - 1; i++) {
    opt = argv[i];

    /*----------------------------------------------------------*
     * -a, --report-imports : 					*
     *   Show all reports except in standard package.		*
     *----------------------------------------------------------*/

    if(strcmp(opt, "-a") == 0 || strcmp(opt, "--report-imports")== 0) {
      set_show_all_reports = TRUE;
    }
 
    /*----------------------------------------------------------*
     * -A, --Report-imports :					*
     *   Show all reports, even in standard package.		*
     *----------------------------------------------------------*/

    else if(strcmp(opt, "-A") == 0 || strcmp(opt, "--Report-imports") == 0) {
      show_all_reports = set_show_all_reports = TRUE;
    }
 
    /*----------------------------------------------------------*
     * -b, --behavior : 					*
     *   Turn on behavior checking.				*
     *----------------------------------------------------------*/

    else if(strcmp(opt, "-b") == 0 || strcmp(opt, "--behavior") == 0) {
      err_flags.forever_suppress_property_warnings = 
	err_flags.suppress_property_warnings = 0;
    }
 
    /*----------------------------------------------------------*
     * -c, --start-in-comment :					*
     *    Start reading the package in a long comment.		*
     *----------------------------------------------------------*/

    else if(strcmp(opt, "-c") == 0 || 
	    strcmp(opt, "--start-in-comment") == 0) {
      start_in_comment_mode = TRUE;
    }

    /*----------------------------------------------------------*
     * -d, --abbreviated-listing : 				*
     *   Turn off listing, but show reports even though		*
     *   a listing is not being given.				*
     *----------------------------------------------------------*/

    else if(strcmp(opt, "-d") == 0 || 
	    strcmp(opt, "--abbreviated-listing")== 0) {
      do_gen_listing = 0;
      list_reports_without_listing = TRUE;
    }

    /*----------------------------------------------------------*
     * -e, --expert :						*
     *   Set expert mode.					*
     *----------------------------------------------------------*/

    else if(strcmp(opt, "-e") == 0 || strcmp(opt, "--expert") == 0) {
      err_flags.novice = FALSE;
    }
 
    /*----------------------------------------------------------*
     * -eFILE: Set error file for appending.			*
     *----------------------------------------------------------*/

    else if(prefix("-e", opt)) {
      get_out_file("error file", &ERR_FILE, argc, argv, &i, 
		   TEXT_APPEND_OPEN, 2);
    }
 
    /*----------------------------------------------------------*
     * -EFile: Set error file for writing (truncating first).	*
     *----------------------------------------------------------*/

    else if(prefix("-E", opt)) {
      get_out_file("error file", &ERR_FILE, argc, argv, &i, 
		   TEXT_WRITE_OPEN, 2);
    }
 
    /*----------------------------------------------------------*
     * -f, --full-listing : 					*
     *   Turn on full listing.					*
     *----------------------------------------------------------*/

    else if(strcmp(opt, "-f") == 0 || strcmp(opt, "--full-listing") == 0)  {
      if(LISTING_FILE != NULL) do_gen_listing = 2;
    }

    /*----------------------------------------------------------*
     * -F, --Full-listing : 					*
     *   Turn on complete listing.				*
     *----------------------------------------------------------*/

    else if(strcmp(opt, "-F") == 0 || strcmp(opt, "--Full-listing") == 0)  {
      if(LISTING_FILE != NULL) do_gen_listing = 3;
    }

    /*----------------------------------------------------------*
     * -Mh : Set ideWindow for done message.			*
     *----------------------------------------------------------*/

#   ifdef MSWIN
      else if(prefix("-M", opt)) {
	sscanf(opt+2, "%d", &ideWindow);
      }
#   endif

    /*----------------------------------------------------------*
     * --help : 						*
     *    Ask for usage information.			 	*
     *----------------------------------------------------------*/

    else if(strcmp(opt, "--help") == 0) {
      do_help= TRUE;
    }

    /*----------------------------------------------------------*
     * -i, --no-check-indent : 					*
     *    Turn off indentation checking.			*
     *----------------------------------------------------------*/

    else if(strcmp(opt, "-i") == 0 ||
            strcmp(opt, "--no-check-indent") == 0) {
      err_flags.forever_check_indentation = 
	err_flags.check_indentation = FALSE;
    }

    /*----------------------------------------------------------*
     * -IPATH, --importPATH : 					*
     *   Set import path.					*
     *----------------------------------------------------------*/

    else if(prefix("-I", opt)) {
      char* carg = (opt[2] != '\0') ? opt+2 : argv[++i];
      SET_LIST(default_import_path, str_cons(carg, default_import_path));
    }
    else if(prefix("--import", opt)) {
      char* carg = (opt[8] != '\0') ? opt+8 : argv[++i];
      SET_LIST(default_import_path, str_cons(carg, default_import_path));
    }

    /*------------------------------------------------------------*
     * -k, --no-check-exhaustive : 				  *
     *    Suppress warnings about patterns not being exhaustive.  *
     *------------------------------------------------------------*/

    else if(strcmp(opt, "-k") == 0 || 
	    strcmp(opt, "--no-check-exhaustive") == 0) {
      err_flags.forever_suppress_pm_incomplete_warnings = TRUE;
    }

    /*----------------------------------------------------------*
     * -l, --no-listing : 					*
     *   Turn off listing.					*
     *----------------------------------------------------------*/

    else if(strcmp(opt, "-l") == 0 || strcmp(opt, "--no-listing") == 0)  {
      do_gen_listing = 0;
      LISTING_FILE = NULL;
    }

    /*----------------------------------------------------------*
     * -LFILE, --listingFILE : 					*
     *   Set listing file.					*
     *----------------------------------------------------------*/

    else if(prefix("-L", opt)) {
      get_out_file("listing file", &LISTING_FILE, argc, argv, &i, 
		   TEXT_WRITE_OPEN, 2);
      ERR_FILE = LISTING_FILE;
    }
    else if(prefix("--listing", opt)) {
      get_out_file("listing file", &LISTING_FILE, argc, argv, &i, 
		   TEXT_WRITE_OPEN, 9);
      ERR_FILE = LISTING_FILE;
    }

    /*----------------------------------------------------------*
     * -ni : Turn off code improvement.				*
     *----------------------------------------------------------*/

    else if(strcmp(opt, "-ni") == 0) suppress_code_improvement = TRUE;

    /*----------------------------------------------------------*
     * -ns : Suppress reading of standard.ast.			*
     *----------------------------------------------------------*/

    else if(strcmp(opt, "-ns") == 0) no_load_standard = TRUE;

    /*----------------------------------------------------------*
     * -nw, --no-warn : 					*
     *   Suppress all warnings.					*
     *----------------------------------------------------------*/

    else if(strcmp(opt, "-nw") == 0 || strcmp(opt, "--no-warn") == 0) {
      err_flags.forever_suppress_warnings = TRUE;
    }

    /*----------------------------------------------------------*
     * -pN : Set pattern match/expand substitution depth to N.	*
     *----------------------------------------------------------*/

    else if(prefix("-p", opt)) {
      char* carg = (opt[2] != '\0') ? opt+2 : argv[++i];
      if(sscanf(carg, "%ld", &max_patmatch_subst_depth) <= 0) usage_err();
    }

    /*----------------------------------------------------------*
     * -s, --show : 						*
     *    Cause show_types to be done at a type error.		*
     *----------------------------------------------------------*/

    else if(strcmp(opt, "-s") == 0 || strcmp(opt, "--show") == 0) {
      do_show_at_type_err = TRUE;
    }

    /*----------------------------------------------------------*
     * --version : 						*
     *    Ask for version information.			 	*
     *----------------------------------------------------------*/

    else if(strcmp(opt, "--version") == 0) {
      do_version = TRUE;
    }

    /*----------------------------------------------------------*
     * --verbose : 						*
     *    Ask for verbose mode.					*
     *----------------------------------------------------------*/

    else if(strcmp(opt, "--verbose") == 0) {
      verbose_mode = TRUE;
    }

    /*----------------------------------------------------------*
     * -w, --warn : 						*
     *   Override any suppressed warnings.  Give the 		*
     *   warnings anyway.					*
     *----------------------------------------------------------*/

    else if(strcmp(opt, "-w") == 0 || strcmp(opt, "--warn") == 0) {
      err_flags.no_suppress_warnings = TRUE;
    }

    /*----------------------------------------------------------*
     * -1 : Stop after first declaration that causes an error.	*
     *----------------------------------------------------------*/

    else if(strcmp(opt, "-1") == 0)  stop_at_first_err = TRUE;

# ifdef DEBUG

    /*----------------------------------------------------------*
     * -T     : Make the trace file the same as the listing	*
     *		file.						*
     * -TFILE : Set the trace file to FILE.			*
     *----------------------------------------------------------*/

    else if(prefix("-T", opt)) {
      if(opt[2] == '\0') TRACE_FILE = LISTING_FILE;
      else {
        TRACE_FILE = fopen_file(opt + 2, TEXT_WRITE_OPEN);
        if(TRACE_FILE == NULL) die(19);
      }
    }

    /*----------------------------------------------------------*
     * -DXXX: Set a debug option.				*
     *----------------------------------------------------------*/

    else if(set_inline_debug(opt, "-D", 2) > 0) {
#     ifdef YYDEBUG
        if(strcmp(opt, "-DYY") == 0) {
	  do_yydebug = 1; yydebug = 0;
        }
#     endif
    }

    /*----------------------------------------------------------*
     * -DTAB: Cause tables to be dumped at end of compile.	*
     *----------------------------------------------------------*/

    else if(strcmp(opt, "-DTAB") == 0)  print_tables = 1;
# endif


    /*----------------------------------------------------------*
     * Bad option: Complain and exit.				*
     *----------------------------------------------------------*/

    else usage_err();
  }
}


/****************************************************************
 *				MAIN				*
 ****************************************************************/

#ifdef MSWIN
int ast_main(int argc, char **argv)
#else
int main(int argc, char **argv)
#endif
{
  char *ast_imports;
  char *this_file, *this_file_ast;
  struct stat stat_buf;

  /*---------------------------------------------------------------------*
   ***** If there are no arguments, then show the command line       *****
   ***** options.  If version is requested, show it.		     *****
   *---------------------------------------------------------------------*/

# ifdef UNIX
    if(argc == 1 || do_help) {
      show_astc_options();
      return 0;
    }
    if(do_version) {
      printf("astc version %s\n", ASTC_VERSION);
      return 0;
    }
# endif

  /*----------------------------------------------------*
   * If this is an instrumented run, then set up	*
   * the instrumentation.				*
   *----------------------------------------------------*/

# ifdef INSTRUMENT
    zzinit();
# endif

  /*---------------------------------------------------------------------*
   ***** Handle interrupts and segmentation violations in sane ways. *****
   *---------------------------------------------------------------------*/

  signal(SIGINT, intrupt);
  signal(SIGSEGV, segviol);

  /*-------------------------------------------------------------------*
   **** Get the profile for MSWIN version.  The profile tells where ****
   **** things are located.                                         ****
   *-------------------------------------------------------------------*/

# ifdef MSWIN
    get_profile();
# endif

  /*-------------------------------------------------------------------*
   ****          Output files -- defaults.                          ****
   *-------------------------------------------------------------------*/

# ifdef UNIX
    LISTING_FILE = stdout;
    ERR_FILE     = stdout;
#   ifdef DEBUG
      TRACE_FILE = stdout;
#   endif
# endif

# ifdef MSWIN
    {char* s = (char*) BAREMALLOC(strlen(MESSAGE_DIR) + 
				  strlen(ERR_FILE_NAME) + 1);
     sprintf(s, "%s%s", MESSAGE_DIR, ERR_FILE_NAME);
     LISTING_FILE = NULL;
     ERR_FILE = fopen_file(s, TEXT_WRITE_OPEN);
     FREE(s);
    }
#   ifdef DEBUG
      TRACE_FILE = NULL;
#   endif
# endif

  /*---------------------------------------------------------------------*
   **** Initialize storage allocation right away, since we will need  ****
   **** it.  Also initialize the string table right away.	      ****
   *---------------------------------------------------------------------*/

  init_alloc();
  init_str_tbl();

  /*---------------------------------------------------------------------*
   **** Get the default import search path.  This comes from environment *
   **** variable AST_IMPORTS if that variable is defined, and is         *
   **** [.,STD_DIR] when AST_IMPORTS is not defined. where STD_DIR is    *
   **** the directory where the standard library is located.             *
   *---------------------------------------------------------------------*/

  ast_imports = getenv("AST_IMPORTS");
  if(ast_imports == NULL) {
    default_import_path = str_cons(".", str_cons(STD_DIR, NIL));
  }
  else {
    default_import_path = file_colonsep_to_list(ast_imports);
  }
  bump_list(default_import_path);


  /*-------------------------------------------------------------------*
   **** Read the command line and set the options that it calls for ****
   *-------------------------------------------------------------------*/
 
  if(argc == 1 || argv[argc-1][0] == '-') usage_err();
  process_command_line_options(argc, argv);

  /*----------------------------------------------------------------*
   ****                Main Initialization 			 ****
   *----------------------------------------------------------------*/

  gen_listing = 0;
  copy_expect_types = FALSE;
# ifdef DEBUG
    set_traces(trace_preamble);
# endif
  init_modes();
  init_std_ids();
  init_loctbl_tm();
  init_properties();
  standard_package_name = stat_id_tb(STANDARD_AST_NAME);
  alt_standard_package_name = stat_id_tb(ALT_STANDARD_AST_NAME);

  /*----------------------------------------------------------------------*
   **** Get the file to compile.  Set compiling_standard_asi if the    ****
   **** file being compiled is standard.asi.  Also open the index file ****
   **** and description file.	 				       ****
   *----------------------------------------------------------------------*/

  this_file_ast = main_file_name = ast_name(argv[argc-1], 0);
  {int this_file_len = strlen(this_file_ast);
   char* this_dir = (char*) BAREMALLOC(this_file_len + 1);
   char* fname    = (char*) BAREMALLOC(this_file_len + 1);
   
   /*---------------------------------------------------------------*
    * Pull the file name apart into directory and simple file name. *
    * Determine if this is standard.asi.			    *
    *---------------------------------------------------------------*/

   dir_prefix(this_dir, fname, this_file_ast);
   compiling_standard_asi = lcequal(fname, STANDARD_AST_NAME ".asi");

   /*-----------------------------------------------*
    * Open the description file and the index file. *
    *-----------------------------------------------*/

   open_description_file(this_file_ast);
   open_index_file(this_dir, fname);
   FREE(fname);
   FREE(this_dir);
  }
  this_file = this_file_ast;
  this_file_ast = ast_name(this_file, 1);
  if(stat_file(this_file_ast, &stat_buf) != 0) {
    fprintf(ERR_FILE, "astc: cannot read file %s\n", this_file_ast);
    clean_up_and_exit(1);
  }

  /*--------------------------------------------------------------------*
   **** Initialize the lexer and open the source file.  Write a      ****
   **** heading on the listing file, if a listing is called for.     ****
   *--------------------------------------------------------------------*/

  init_reserved_words_l();
  if(!init_lexical_l(this_file)) {
    if(error_occurred) clean_up_and_exit(1);
  }
  else {
    if(do_gen_listing && file_info_st->next != NULL) {
      time_t tloc;
      time(&tloc);
      fprintf(LISTING_FILE, "%s", ctime(&tloc));
      fprintf(LISTING_FILE, "ECU Astarte, version %s\nFile ", ASTC_VERSION);
      fprint_external(LISTING_FILE, "%s\n\n", file_info_st->next->file_name);
    }
  }
  gen_listing = do_gen_listing;

  /*--------------------------------------------------------------------*
   **** Print the initial line number, suppressed by init_lexical_l. ****
   **** Prepare the lexer for the first line.			     ****
   *--------------------------------------------------------------------*/

  if(gen_listing> 0 && gen_listing < 3) {
    fprintf(LISTING_FILE, "   1 "); 
  }
  else current_line_number--;
  new_line_l();

  /*--------------------------------------------------------------------*
   ****                  More initialization                         ****
   *--------------------------------------------------------------------*/

# ifdef DEBUG
    set_traces(trace_standard);
# endif

  init_tables_tm();
  init_class_tbl_tm();
  init_types();
  init_roles();
  init_exprs();
# ifdef DEBUG
    if(trace) trace_t(465);
# endif

  /*------------------------------------------------------------------*
   ****             Parse and translate the program                ****
   *------------------------------------------------------------------*/

  yyparse();

  /*------------------------------------------------------------------*
   ****                    Finish up                               ****
   *------------------------------------------------------------------*/

# ifdef DEBUG
    if(print_tables) {
      trace_t(466);
      print_ent_table();
      print_type_table();
      print_intersect_table();
    }
# endif

  clean_up_and_exit(0);
  return 0;  /* Not reached, but keeps compiler happy */
}


/****************************************************************
 *			HANDLE_OPTION				*
 ****************************************************************
 * Handle an option in an advisory dcl. The option is given by  *
 * inopt.  Parameter all is true if the option is accompanied   *
 * with 'all', false if it is accompanied with 'one'.           *
 ****************************************************************/

/*-------------------------------------------------------------------*
 * Array compiler_opts tells how to handle options. The array should *
 * end with an entry with optname = NULL.			     *
 *-------------------------------------------------------------------*/

PRIVATE struct {
  char *optname;	/* Name of an option 			*/
  Boolean *optvar;	/* Variable to set for one or all 	*/
  Boolean *alloptvar;   /* Variable to set for all.       	*/
  char canonval;	/* Value to set to in positive form.    */
			/* Set to !canonval for negative form.  */
} FARR compiler_opts[] =

{ 
  {"showlocals",
   &show_types,
   &show_all_types, 2},

  {"show",
    &show_types,
    &show_all_types, 1},

  {"echo",
   &echo_expr,
   &echo_all_exprs, 1},

  {"showExpansions",
   &should_show_patmatch_subst,
   &always_should_show_patmatch_subst, 1},

  {"trackTrappedFailure", 
   &ignore_trapped_exceptions,
   &forever_ignore_trapped_exceptions, 0},

  {"warnmissingDefinition", 
   &err_flags.suppress_missing_warnings,
   &err_flags.forever_suppress_missings, 0},

  {"warndefaults",
    &err_flags.suppress_dangerous_default_warnings,
    &err_flags.forever_suppress_dangerous_default_warnings, 0},

  {"warnnotExhaustive",    
    &err_flags.suppress_pm_incomplete_warnings,
    &err_flags.forever_suppress_pm_incomplete_warnings, 0},

  {"warnbehavior", 
   &err_flags.suppress_property_warnings,
   &err_flags.forever_suppress_property_warnings, 0},

  {"warnshadow",
   &err_flags.suppress_global_shadow_warnings,
   &err_flags.forever_suppress_global_shadow_warnings, 0},

  {"warnindent",
   &err_flags.check_indentation,
   &err_flags.forever_check_indentation, 1},

  {"warn",          
   &err_flags.suppress_warnings, 
   &err_flags.forever_suppress_warnings, 0},

  {"warnunused",   
   &err_flags.suppress_unused_warnings,
   &err_flags.forever_suppress_unused_warnings, 0},

  {"tro", 	    
   &suppress_tro, 
   &forever_suppress_tro, 0},

  {NULL, NULL, NULL, 0}
};

/*----------------------------------------------------------*/

void handle_option(char *inopt, Boolean all)
{
  int k;
  Boolean val, negate;
  char *opt;

  opt = inopt;
  if(opt == NULL) return;

  /*-----------------------*
   * Handle option "stop". *
   *-----------------------*/

  if(strcmp(opt, "stop") == 0) {
    die(175);
  }

  /*---------------------*
   * Handle prefix "no". *
   *---------------------*/

  negate = FALSE;
  if(prefix("no", opt)) {
    negate = TRUE;
    opt += 2;
  }

  /*----------------------*
   * Handle main options. *
   *----------------------*/

  for(k = 0; compiler_opts[k].optname != NULL; k++) {
    if(strcmp(opt, compiler_opts[k].optname) == 0) {
      if(err_flags.no_suppress_warnings && prefix("warn", opt)) return;
      val = compiler_opts[k].canonval;
      if(negate) val = !val;
      if(all) *(compiler_opts[k].alloptvar) = val;
      *(compiler_opts[k].optvar) = val;
      return;
    }
  }

  /*------------------------------*
   * Handle behavior warn/nowarn. *
   *------------------------------*/

  if(prefix("warn", opt)) {
    opt += 4;
    if(all) {
      if(negate) global_suppress_property(opt);
      else global_unsuppress_property(opt);
    }
    else local_suppress_property(opt, negate);
    return;
  }

  /*---------------------------*
   * Handle debugging options. *
   *---------------------------*/

# ifdef DEBUG
    if(strcmp(opt, "debug") == 0) {
      if(negate) set_traces(0);
      else trace = 1;
      return;
    }
    else if((set_inline_debug(opt, "debug", 1)) > 0) return;
# endif
 
  syntax_error1(BAD_ADVISORY_ERR, inopt, 0);
}




