#define	L1_OP	257
#define	L2_OP	258
#define	L3_OP	259
#define	L4_OP	260
#define	L5_OP	261
#define	L6_OP	262
#define	L7_OP	263
#define	L8_OP	264
#define	L9_OP	265
#define	R1_OP	266
#define	R2_OP	267
#define	R3_OP	268
#define	R4_OP	269
#define	R5_OP	270
#define	R6_OP	271
#define	R7_OP	272
#define	R8_OP	273
#define	R9_OP	274
#define	COMPARE_OP	275
#define	BAR_OP	276
#define	COLON_EQUAL_OP	277
#define	UNARY_OP	278
#define	ABBREV_TOK	279
#define	ABSTRACTION_TOK	280
#define	ADVISORY_TOK	281
#define	AND_TOK	282
#define	ASSUME_TOK	283
#define	ASK_TOK	284
#define	ATOMIC_TOK	285
#define	AWAIT_TOK	286
#define	BODY_TOK	287
#define	BRING_TOK	288
#define	BUT_IF_FAIL_TOK	289
#define	BY_TOK	290
#define	CASE_TOK	291
#define	CATCHING_TOK	292
#define	CHOOSE_TOK	293
#define	CLASS_TOK	294
#define	CONST_TOK	295
#define	CONSTRAINT_TOK	296
#define	CONSTRUCTOR_TOK	297
#define	CONTEXT_TOK	298
#define	CONTINUE_TOK	299
#define	DEFAULT_TOK	300
#define	DESCRIPTION_TOK	301
#define	DIRECTORY_TOK	302
#define	DO_TOK	303
#define	ELSE_TOK	304
#define	EXCEPTION_TOK	305
#define	EXECUTE_TOK	306
#define	EXPECT_TOK	307
#define	EXPORT_TOK	308
#define	EXTENSION_TOK	309
#define	EXTRACT_TOK	310
#define	LCEXTRACT_TOK	311
#define	FOR_TOK	312
#define	FROM_TOK	313
#define	HOLDING_TOK	314
#define	IF_TOK	315
#define	IMPLEMENTS_TOK	316
#define	IMPLIES_TOK	317
#define	IMPORT_TOK	318
#define	INTERFACE_TOK	319
#define	ISA_TOK	320
#define	LET_TOK	321
#define	LOOP_TOK	322
#define	LOOPCASE_TOK	323
#define	MATCH_TOK	324
#define	MATCHING_TOK	325
#define	MISSING_TOK	326
#define	MIXED_TOK	327
#define	OPEN_TOK	328
#define	OPERATOR_TOK	329
#define	OR_TOK	330
#define	PACKAGE_TOK	331
#define	PATTERN_TOK	332
#define	LCPATTERN_TOK	333
#define	RELATE_TOK	334
#define	SPECIES_TOK	335
#define	SPECIES_AS_VAL_TOK	336
#define	STREAM_TOK	337
#define	SUBCASES_TOK	338
#define	TARGET_TOK	339
#define	TEAM_TOK	340
#define	THEN_TOK	341
#define	TRAP_TOK	342
#define	LCTRAP_TOK	343
#define	VAR_TOK	344
#define	WHICH_TOK	345
#define	WHERE_TOK	346
#define	WHEN_TOK	347
#define	WITH_TOK	348
#define	WHILE_TOK	349
#define	END_TOK	350
#define	LINE_TOK	351
#define	LPAREN_TOK	352
#define	RPAREN_TOK	353
#define	LBRACE_TOK	354
#define	RBRACE_TOK	355
#define	LBRACK_TOK	356
#define	RBRACK_TOK	357
#define	LWRAP_TOK	358
#define	RWRAP_TOK	359
#define	LBRACK_COLON_TOK	360
#define	RBRACK_COLON_TOK	361
#define	LROLE_SELECT_TOK	362
#define	RROLE_SELECT_TOK	363
#define	LROLE_MODIFY_TOK	364
#define	LLAZY_TOK	365
#define	RLAZY_TOK	366
#define	LPAREN_DBLBAR_TOK	367
#define	RPAREN_DBLBAR_TOK	368
#define	LBOX_TOK	369
#define	RBOX_TOK	370
#define	COMMA_TOK	371
#define	COLON_TOK	372
#define	SEMICOLON_TOK	373
#define	ROLE_MARK_TOK	374
#define	SGL_ARROW_TOK	375
#define	DBL_ARROW_TOK	376
#define	AMPERSAND_TOK	377
#define	EQUAL_TOK	378
#define	PLUS_EQUAL_TOK	379
#define	COLON_EQUAL_TOK	380
#define	BAR_TOK	381
#define	QUESTION_MARK_TOK	382
#define	PERIOD_TOK	383
#define	CHAR_CONST_TOK	384
#define	NAT_CONST_TOK	385
#define	REAL_CONST_TOK	386
#define	STRING_CONST_TOK	387
#define	PAT_VAR_TOK	388
#define	PROC_ID_TOK	389
#define	UNKNOWN_ID_TOK	390
#define	COMM_ID_TOK	391
#define	FAM_ID_TOK	392
#define	TYPE_ID_TOK	393
#define	FAM_VAR_TOK	394
#define	TYPE_VAR_TOK	395
#define	GENUS_ID_TOK	396
#define	TYPE_ABBREV_TOK	397
#define	FAM_ABBREV_TOK	398
#define	FAM_MACRO_TOK	399
#define	FAM_VAR_ABBREV_TOK	400
#define	GENUS_ABBREV_TOK	401
#define	COMM_ABBREV_TOK	402
#define	RECOVER	403
#define	IDENTIFIER	404
#define	JUXTAPOSITION	405


extern YYSTYPE yylval;
/************************************************************************
 * File: parser/tokmod.h
 * The contents of this file are appended to tokens.h
 ************************************************************************/

/**************************************************************
 * Note: If you are reading file tokens.h, do not modify it.  *
 * This part comes from file parser/tokmod.h.  The rest is    *
 * automatically generated by the parser generator.  You may  *
 * modify parser/tokmod.h. 				      *
 **************************************************************/

#define FIRST_RESERVED_WORD_TOK ABBREV_TOK
#define LAST_RESERVED_WORD_TOK	WHILE_TOK

/***************************************************************
 * The following are for converting tokens to smaller numbers. *
 * In the class table, the kind of an species, etc. is stored  *
 * using the code returned by MAKE_CODE.  For example, the     *
 * fact that a given identifier is a species is indicated by   *
 * storing MAKE_CODE(GENUS_ID_TOK) in the code field of the    *
 * table entry.   					       *
 ***************************************************************/

#define CODE_OFFSET	(UNKNOWN_ID_TOK - 1)
#define RW_OFFSET	(FIRST_RESERVED_WORD_TOK - 1)
#define TN_OFFSET	(LPAREN_TOK - 1)
#define MAKE_CODE(tok)  (tok - CODE_OFFSET)
#define MAKE_TOK(code)  (code + CODE_OFFSET)

/*******************************************************************
 * The following are pseudo-tokens.  They are combined with other  *
 * tokens as far as the parser is concerned, and the parser never  *
 * sees these, but they are present in the shadow stack, and are   *
 * used for associating names (lexemes) with tokens.		   *
 *								   *
 * Note: extend these downward if new ones are added.  The largest *
 * code here should be 255.					   *
 *								   *
 * All reserved words whose lexemes start with a lower case letter *
 * should be smaller than or equal to EXITCASE_TOK.		   *
 *******************************************************************/

#define LSHARED_TOK      227    /* <:#					*/
#define RSHARED_TOK      228    /* #:>					*/
#define LNONSHARED_TOK   229    /* <:%					*/
#define RNONSHARED_TOK   230    /* %:>					*/
#define LWRAPQ_TOK 	 231    /* ?<<					*/
#define RWRAPQ_TOK 	 232    /* >>?					*/
#define CATCHINGTERM_TOK 233	/* RW catchingTermination		*/
#define CATCHINGEACH_TOK 234	/* RW catchingEachThread		*/
#define FIRST_TOK      235	/* RW first				*/
#define PERHAPS_TOK    236	/* RW perhaps				*/
#define ONE_TOK	       237	/* RW one				*/
#define ALL_TOK	       238	/* RW all				*/
#define EXITCASE_TOK   239      /* RW exitcase				*/
#define BAD_OP	       240	/* An operator that has been 		*/
				/* inconsistently defined.		*/

#define FIRST_ALT_RESERVED_WORD_TOK EXPAND_TOK
#define EXPAND_TOK     241	/* RW Expand (only on shadow stack)     */
#define ANTICIPATE_TOK 242      /* RW Anticipate (only on shadow stack) */
#define DEFINE_TOK     244	/* RW Define (only on shadow stack)     */
#define RELET_TOK      245      /* RW Relet (only on shadow stack)      */
#define CUTHERE_TOK    249 	/* RW CutHere (only on shadow stack)    */
#define MIX_TOK        250      /* RW Mix (only on shadow stack)        */
#define	UNIQUE_TOK     252	/* RW Unique (ony on shadow st)	        */
#define	TRY_TOK	       254	/* RW Try (only on shadow st)	        */
#define	UNTRAP_TOK     255	/* RW Untrap (only on shadow stack)     */
#define LAST_ALT_RESERVED_WORD_TOK UNTRAP_TOK


/********************************************************
 * The following are only used as tags outside the	*
 * parser, in places where tokens are also used.	*
 ********************************************************/

#define TYPE_LIST_TOK	1

/********************************************************
 * 			TOKEN KINDS			*
 ********************************************************/

#define DCL_BEGIN_K	1	/* Beginning of declaration               */
#define DE_BEGIN_K	2 	/* Beginning of declaration or expression */
#define EXPR_BEGIN_K	3	/* Beginning of expr that does not admit  */
				/* semicolons                             */
#define SEMI_BEGIN_K	4	/* Beginning of expr that admits semicolons */
#define LPAREN_K	5	/* Left parenthesis or bracket            */
#define END_K		6	/* End word or period                     */
#define RPAREN_K	7	/* Right parenthesis or bracket           */
#define OTHER_K		8
#define BEGIN_K         9       /* Begin word (used for push back)        */
#define SEPARATOR_K	10      /* A separator (used for push back)       */
