/************************************************************************
 * File: parser/tokmod.h
 * The contents of this file are appended to tokens.h
 ************************************************************************/

/**************************************************************
 * Note: If you are reading file tokens.h, do not modify it.  *
 * This part comes from file parser/tokmod.h.  The rest is    *
 * automatically generated by the parser generator.  You may  *
 * modify parser/tokmod.h. 				      *
 **************************************************************/

#define FIRST_RESERVED_WORD_TOK ABBREV_TOK
#define LAST_RESERVED_WORD_TOK	WHILE_TOK

/***************************************************************
 * The following are for converting tokens to smaller numbers. *
 * In the class table, the kind of an species, etc. is stored  *
 * using the code returned by MAKE_CODE.  For example, the     *
 * fact that a given identifier is a species is indicated by   *
 * storing MAKE_CODE(GENUS_ID_TOK) in the code field of the    *
 * table entry.   					       *
 ***************************************************************/

#define CODE_OFFSET	(UNKNOWN_ID_TOK - 1)
#define RW_OFFSET	(FIRST_RESERVED_WORD_TOK - 1)
#define TN_OFFSET	(LPAREN_TOK - 1)
#define MAKE_CODE(tok)  (tok - CODE_OFFSET)
#define MAKE_TOK(code)  (code + CODE_OFFSET)

/*******************************************************************
 * The following are pseudo-tokens.  They are combined with other  *
 * tokens as far as the parser is concerned, and the parser never  *
 * sees these, but they are present in the shadow stack, and are   *
 * used for associating names (lexemes) with tokens.		   *
 *								   *
 * Note: extend these downward if new ones are added.  The largest *
 * code here should be 255.					   *
 *								   *
 * All reserved words whose lexemes start with a lower case letter *
 * should be smaller than or equal to EXITCASE_TOK.		   *
 *******************************************************************/

#define LSHARED_TOK      227    /* <:#					*/
#define RSHARED_TOK      228    /* #:>					*/
#define LNONSHARED_TOK   229    /* <:%					*/
#define RNONSHARED_TOK   230    /* %:>					*/
#define LWRAPQ_TOK 	 231    /* ?<<					*/
#define RWRAPQ_TOK 	 232    /* >>?					*/
#define CATCHINGTERM_TOK 233	/* RW catchingTermination		*/
#define CATCHINGEACH_TOK 234	/* RW catchingEachThread		*/
#define FIRST_TOK      235	/* RW first				*/
#define PERHAPS_TOK    236	/* RW perhaps				*/
#define ONE_TOK	       237	/* RW one				*/
#define ALL_TOK	       238	/* RW all				*/
#define EXITCASE_TOK   239      /* RW exitcase				*/
#define BAD_OP	       240	/* An operator that has been 		*/
				/* inconsistently defined.		*/

#define FIRST_ALT_RESERVED_WORD_TOK EXPAND_TOK
#define EXPAND_TOK     241	/* RW Expand (only on shadow stack)     */
#define ANTICIPATE_TOK 242      /* RW Anticipate (only on shadow stack) */
#define DEFINE_TOK     244	/* RW Define (only on shadow stack)     */
#define RELET_TOK      245      /* RW Relet (only on shadow stack)      */
#define CUTHERE_TOK    249 	/* RW CutHere (only on shadow stack)    */
#define MIX_TOK        250      /* RW Mix (only on shadow stack)        */
#define	UNIQUE_TOK     252	/* RW Unique (ony on shadow st)	        */
#define	TRY_TOK	       254	/* RW Try (only on shadow st)	        */
#define	UNTRAP_TOK     255	/* RW Untrap (only on shadow stack)     */
#define LAST_ALT_RESERVED_WORD_TOK UNTRAP_TOK


/********************************************************
 * The following are only used as tags outside the	*
 * parser, in places where tokens are also used.	*
 ********************************************************/

#define TYPE_LIST_TOK	1

/********************************************************
 * 			TOKEN KINDS			*
 ********************************************************/

#define DCL_BEGIN_K	1	/* Beginning of declaration               */
#define DE_BEGIN_K	2 	/* Beginning of declaration or expression */
#define EXPR_BEGIN_K	3	/* Beginning of expr that does not admit  */
				/* semicolons                             */
#define SEMI_BEGIN_K	4	/* Beginning of expr that admits semicolons */
#define LPAREN_K	5	/* Left parenthesis or bracket            */
#define END_K		6	/* End word or period                     */
#define RPAREN_K	7	/* Right parenthesis or bracket           */
#define OTHER_K		8
#define BEGIN_K         9       /* Begin word (used for push back)        */
#define SEPARATOR_K	10      /* A separator (used for push back)       */
